spring.application.name=zumi_backend
# ===============================
# = DATA SOURCE
# ===============================
# Set here configurations for the database connection
spring.datasource.url=jdbc:postgresql://localhost:5433/zumidb
spring.datasource.username=postgres
spring.datasource.password=geheim123
spring.datasource.driver-class-name=org.postgresql.Driver
# ===============================
# = JPA / HIBERNATE
# ===============================
# Show or not log for each sql query
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
